### ISSUE TITLE
解析某些apk出错

### ISSUE THREAD

**Issue by hanks-zyh** [kiya-z/parse-apk#4]
[apk](http://openbox.mobilem.360.cn/index/d/sid/2950353)

运行后出现乱码

**Comment by kiyadesu** [comment]
@hanks-zyh 解析的是dex啊，你不会弄的 apk 吧，我这没问题呀

**Comment by hanks-zyh** [comment]
@kiya-z  dex是直接 解压apk的出来的吗,还是反编译出来的? 可以将这个步骤放到 shell命令中,不然的话太麻烦了

**Comment by kiyadesu** [comment]
@hanks-zyh apk那个还没写好呢呀，后来放那了，因为那时候清单文件不知道咋解析呀，过几天在写，现在管用的是dex的解析

**Comment by kiyadesu** [comment]
@hanks-zyh dex是解压出来的
